### ISSUE TITLE
[SUGGESTION] Refinery Multiblock

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Gliese-832-c/ad-astra-per-nucleon#10]
Create a refinery multiblock (at least 5^3 in size?) that is an upgrade over TE's fractionating stills.
The refinery multiblock will have all the fuel refining recipes, done at a faster rate and in larger batches (each recipe would take as input at least a bucket of fuel). Of course, this will come at a higher energy cost than the regular machines, as well as a higher resource cost!

**Comment by Gliese-832-c** [comment]
Good idea. I'll probably get to it after I'm done with the structure I'm currently working on.

**Comment by Gliese-832-c** [comment]
I think I might do it in the form of a distillation tower, similar to Immersive Petroleum.

**Comment by Gliese-832-c** [comment]
Immersive Petroleum is literally being added, thus fulfilling your request. It just took a cool 8 months and 1 day...
