### ISSUE TITLE
[SUGGESTION] Rework ViesCraft Airships

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Gliese-832-c/ad-astra-per-nucleon#11]
The VC Airships crafting recipes are fairly annoying, due to being based around vanilla-only crafting ingredients.
We have talked in the past about changing the recipes but it's been a long ass while, so I'm bringing the issue back up for consideration 😛 

I don't have any ideas (yet) on how recipes should look like, but they should definitely use more modded stuffs!

**Comment by Gliese-832-c** [comment]
Yup, wanted to do this for a long time, thanks for reminding me.

**Comment by Gliese-832-c** [comment]
More like "Remove ViesCraft Airships"...this doesn't apply anymore, now that the mod is being removed.
