### ISSUE TITLE
[SUGGESTION] Fix Decalithium Fuel Chain Progression

### ISSUE THREAD

**Issue by kubulll** [Gliese-832-c/ad-astra-per-nucleon#14]
So because with 0.10 version we will get dilithium and we will be able to make decalitium, problem is after calculations you would need to spend around 34 years of pure reactor time using 600 cells to just get 1 destabilized decalithium which is unbalnced and just plain stupid.So i suggest making it more managable for example: rchange fuel reprocessing from small shards to normal shards which would already take it down from 34 years to 16 days which is now managable but still little too long considering its calculated on 2.5x fuel time and 600 cells. Another option would be to change completely change how its processed and use nukes of other machines. Last option would be removing destabilizied decalithium from alot of recipes and use normal decalithium.

I also didn't account Cf or dilithium needed so even 1 small destabilized decalithium crystal shard would require several megaveins. You could also increase how much radiation it produces.

**Comment by Gliese-832-c** [comment]
Yeah, I will probably remove the small shards.

**Comment by Gliese-832-c** [comment]
Fixed in v0.10! I changed the recipes to output normal shards instead of small shards. More testing needs to be done, but for now, the production time should have been reduced by a factor of 729.
