### ISSUE TITLE
[BUG] Brightness slider doesn't work and appears to glitch out

### ISSUE THREAD

**Issue by RedstoneRob** [Gliese-832-c/ad-astra-per-nucleon#17]
**Describe the bug**
When entering a world, the brightness is on Moody. When going into the video settings to increase the brightness, the brightness slider doesn't appear like a slider and cannot be adjusted, only displaying a percentage value. When F11 is pressed, switching between fullscreen and windowed mode, the slider reverts back to normal and can be used. However, it doesn't appear to actually adjust the brightness and will revert back to the broken state when the GUI options menu is closed and re-opened.
**To Reproduce**
Open a world in 0.10 and look in video settings. It does seem to occur even in worlds that have been freshly loaded in 0.10.

**Screenshots**
(I hope these work. These are the broken state of the slider, the fixed state, and the moody brightness despite the slider being on bright)
![2020-11-10_21 18 41](https://user-images.githubusercontent.com/56180685/98758389-af6da180-239c-11eb-8c9d-8b2f7c84aa5b.png)
![2020-11-10_21 18 54](https://user-images.githubusercontent.com/56180685/98758403-b5638280-239c-11eb-8b87-7b64b8c4cd99.png)
![2020-11-10_21 19 15](https://user-images.githubusercontent.com/56180685/98758412-bac0cd00-239c-11eb-8b95-ed8bdf652e08.png)

**Comment by Gliese-832-c** [comment]
That's a Hardcore Darkness feature and intended, that slider would destroy the only feature that mod has, so it has been disabled.

**Comment by Gliese-832-c** [comment]
By the way, there's a different mod that adds absolute darkness now which does have a brightness slider. Absolutely dark places will still stay dark, but the slider modifies places where there's at least a bit of light.
