### ISSUE TITLE
[SUGGESTION] Megavein location

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Gliese-832-c/ad-astra-per-nucleon#20]
**Is your suggestion related to a problem? Please describe.**
New/Future players of the pack that haven't been keeping up with the development of it, are unaware of ore distribution (or that it even has Geolosys to begin with, if they don't take the time to read modlist). Thus, when starting out, they don't know where to find ores. 

**Describe the solution you'd like**
I suggest using CT to add JEI info tabs to ores/ore clusters, which detail where an ore megavein can be found (biomes and depth), relative rarity (common, rare, etc) and size. (huge, large, small or ore count estimates)

**Describe alternatives you've considered**
The current way is an image buried somewhere either in this or the eVault discord in the AAPN channel. (makes it hard to find)

**Comment by ThePoleThatFishes** [comment]
Closed as duplicate of #9

**Comment by Gliese-832-c** [comment]
lmao
