### ISSUE TITLE
[SUGGESTION] Add crafting recipe for Creative Storage Upgrade (Storage Drawers)

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#21]
**Is your suggestion related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like having these Creative Storage Upgrades, because in my opinion they are no threat to balancing if you have to craft the from really endgame stuff (For example with Singularities from ae2, 64k-Storage components...). It would just be funny to have a "alternative" to ae2 for mass item storage.

**Describe alternatives you've considered**
Just don't add it?
**Additional context**
no

**Comment by joendter** [comment]
Maybe also consider something like this for creative tinkers upgrades

**Comment by Gliese-832-c** [comment]
You mean the infinite storage upgrade that goes up to 2147483647 items? I'll already add a black hole storage type mod in the future, once I get to Sci-Fi tech. If you actually mean the creative upgrade that duplicates items? No.

**Comment by joendter** [comment]
If u add sth like black hole units it's unnecessary.

**Comment by Gliese-832-c** [comment]
Closing not just for the above reason, but also because this mod isn't in the pack anymore.
