### ISSUE TITLE
[SUGGESTION] Add all time stats for ping pong

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#23]
**Is your suggestion related to a problem? Please describe.**
The ping pong game in the loading screen is a great innovation. But your score is always reset.

**Describe the solution you'd like**
Add a all time counter for AI and human wins below or above the counter for the current match. ~~I would also like to rename the AI to lag.~~

**Comment by Gliese-832-c** [comment]
Nothing I can do, really. You'd have to convince the mod developers to do it.

**Comment by Gliese-832-c** [comment]
Closing for the above reason; contact the author of the mod in question for more.
