### ISSUE TITLE
[SUGGESTION] Make it easier to get lead/silver (galena)

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#25]
**Is your suggestion related to a problem? Please describe.**
I now have searched for more than 2.5 hours for a _biome_ in which galena could spawn and still haven't found one.

**Describe the solution you'd like**
I would like if galena would spawn in more biomes. The current biomes are all kinda flat, but there are many more flat and to plains similar biomes such as grasslands. An alternative solution would be to have every ore occur in oceans and rivers, but in very small quantities. Overall I'm a big fan of this geolosys, but in my opinion the configs are not optimal yet, because I don't think you should have to search more than 2 hours to find a feasible biome, to get some metals required for most progress

**Additional context**
My Worldmap:
![worldmap](https://user-images.githubusercontent.com/71767955/106160804-859b6e00-6186-11eb-8864-1eac62b27b48.gif)

My Stats (Most of the distance by boat originates from my fruitless search):
![2021-01-28_16 34 09](https://user-images.githubusercontent.com/71767955/106160954-aebbfe80-6186-11eb-8568-39ef3b33344e.png)

**Comment by Gliese-832-c** [comment]
Wow, that's an extreme case. There have time where players searched for a while, but never this long. There is an ore processing overhaul planned, and when that will be worked on, I'll take a look at the ore spawn configs too. For now, there's nothing I can really do, but maybe cheat in a few stacks of ore? I don't think it would be too cheaty considering the circumstances.

**Comment by Gliese-832-c** [comment]
Doesn't apply anymore, as the progression has been changed in major ways and there is an ore overhaul update coming anyways.
