### ISSUE TITLE
[SUGGESTION] Make manual gear crafting more expensive, so the gearworking die specialization is worth it

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#28]
**Is your suggestion related to a problem? Please describe.**
Right now it doesn't make any difference whether you craft your gears in a crafting table (or autocrafter) or if you craft them using a Compactor with the gearworking die specialization.

**Describe the solution you'd like**
I would like that you would for normal crafting need additional 4 gear-pieces, each crafted from 4 corresponding nuggets, so making gears with the gearworking die/ tinkers smeltery is 16 nuggets cheaper than just crafting them.
The gear-pieces would have this crafting recipe:
![image](https://user-images.githubusercontent.com/71767955/106386597-0ac89200-63d6-11eb-93f4-fe6a758a2e85.png)
I imagine the crafting recipe for gears then like this, with the nuggets representing the gear-pieces
![image](https://user-images.githubusercontent.com/71767955/106386687-7a3e8180-63d6-11eb-9aea-0974c39f0d69.png)

Maybe it would also be possible to just skip the gear-pieces and directly use nuggets for extra cost...
It would also nicely fit to the basice machine chassis that you at first have to craft expensively with iron and later can be made out of bioplastic.

**Comment by joendter** [comment]
Also you could then maybe remove the gear-cast from tinkers...

**Comment by kubulll** [comment]
no nuggets they make your storage messy but something to make them more expensive would be ok

**Comment by joendter** [comment]
you need nuggets anyway for other things...
for example techguns
and iron nuggets for servos but you usually don't need iron gears...

**Comment by kubulll** [comment]
i think you only need nuggets for TG ammo but that is if you are not using press

**Comment by joendter** [comment]
and for flint and steels...

**Comment by Gliese-832-c** [comment]
@kubulll Actually, I like the nuggets idea. It fits @joendter's idea. Basically, it would be very annoying, so it would encourage you to use the machine even more.

**Comment by Gliese-832-c** [comment]
Now that Thermal Expansion is gone, this doesn't apply anymore.
