### ISSUE TITLE
[SUGGESTION] Add a nerfed deep mob learning

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#29]
**Is your suggestion related to a problem? Please describe.**
I hate mobfarms.

**Describe the solution you'd like**
I would like to see deep mob learning in this pack, but with corresponding balancing changes.
First of all I would disable glitch stuff and trials.
Second polymeric clay should require matter: 
with one overworldian matter you can make one polymeric clay, with one hellish matter you can make 4 polymeric clay and with one extraterestrial matter 16 polymeric clay.
For your first polymeric clay you should need a netherstar and other midgame stuff.
The energy costs for simulations should also be increased to begin at like 10 kRF/t for zombies and go up to like 1 MRF/t for wither/ender dragon.
Also the blank models could have a very expensive crafting recipe or maybe be only loot in divers structures...
Also a multiblock simulation chamber would also be nice, and just be more efficient, but I'm not sure how easy this is to realize...

**Comment by Gliese-832-c** [comment]
Unrealistic. What will be done is making it so the player doesn't have to rely on mob drops. The mob overhaul update will still take a while though...
