### ISSUE TITLE
[SUGGESTION] Turbine Rebalancing

### ISSUE THREAD

**Issue by ThePoleThatFishes** [Gliese-832-c/ad-astra-per-nucleon#3]
Thermal Expansion steam is pretty cheese for power gen, therefore it needs to be hit with the nerf hammer!

Rebalancing suggested:
Steam: 4 -> 3 RF/mb, 200% -> 250% Expansion

**Optional Rebalancing**
HPS: 16 -> 18 RF/mb
LPS: 4 -> 4.5 RF/mb
Extreme Blade: 110% -> 108% Efficiency
SiC-SiC Blade: 125% -> 116% Efficiency

In collaboration with @Thalzamar

**Comment by Gliese-832-c** [comment]
I assume that I can configure this in the NuclearCraft configs?

**Comment by Gliese-832-c** [comment]
Indeed, I seem to have found it.

**Comment by Gliese-832-c** [comment]
Added to v0.10-alpha.
