### ISSUE TITLE
[SUGGESTION] Add nc rad resistance to techguns radaway/anti-RAD-pills

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#31]
**Is your suggestion related to a problem? Please describe.**
Even though you can craft neither techgun radaway nor anti-RAD-pills they are still found quite commonly in loot chests.

**Describe the solution you'd like**
I would like if they got nc rad resistance/removal values such as beetroots or golden carrots.

**Describe alternatives you've considered**
Just remove them from the loot tables.

**Comment by ThePoleThatFishes** [comment]
I believe there were plans to sort of integrate the TG radiation items, but they seem to have been forgotten...

**Comment by joendter** [comment]
so just prevent gliese from forgetting it again by spamming out an issue 😛

**Comment by Gliese-832-c** [comment]
Oh, yeah. I wanted to remove them from the structure loottables, so it never would be a problem in the first place. But I never got around to doing it.

**Comment by Gliese-832-c** [comment]
Took me a good 4 and a half months, but I finally added a recipe to convert from the TechGuns items to the NuclearCraft ones.
