### ISSUE TITLE
[SUGGESTION] Add construction site warning sign

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#32]
Since we already have the radiation, generic, electric, biohazard and poison warning sing, I'm missing the construction site sign from chisel 1.7.10. I liked to use it a lot just to fill spaces where later some machine or doorway should go. 
I would also like if the warning signs would get a bit cheaper and more chisel-like, in the way that you don't get only one but 4 or 16 of those per crafting.

**Comment by Gliese-832-c** [comment]
Both things are done in v0.11-alpha! There's a construction site warning sign block and you get 4 of them per craft now!
