### ISSUE TITLE
[SUGGESTION] Add more convenient recipe for dispenser

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#33]
**Is your suggestion related to a problem? Please describe.**
Everyone hates the vanilla dispenser crafting recipe, because it uses a non-stackable-item.

**Describe the solution you'd like**
Add dispenser crafting from 1 dropper 3 strings and 3 sticks. It's overall the same price, the only difference is, that you can craft a stack without too much effort.

**Comment by Gliese-832-c** [comment]
I'll do that, I guess.

**Comment by Gliese-832-c** [comment]
It took me more than 4 and a half months, but I finally did it...
