### ISSUE TITLE
[BUG] Can't craft upgrade template (Storage Drawers) with Extra Drawers drawer

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#34]
**Describe the bug**
Even though the recipe uses oredict i can't use Extra Drawers drawer

![image](https://user-images.githubusercontent.com/71767955/106601047-7ab45500-655b-11eb-94bf-24e291441a7e.png)
![image](https://user-images.githubusercontent.com/71767955/106601104-8e5fbb80-655b-11eb-82cf-cdb024e51313.png)
![image](https://user-images.githubusercontent.com/71767955/106601180-a7686c80-655b-11eb-85d6-005832697fc4.png)

Just add the Extra Drawers Drawers to oredict

**Comment by kubulll** [comment]
They might not be oredicted seems like a mod bug rather than modpack.

**Comment by joendter** [comment]
yeah i will maybe repost this to the mod devs...

**Comment by joendter** [comment]
https://github.com/jaquadro/StorageDrawersExtras/issues/20

**Comment by Gliese-832-c** [comment]
Let's keep it open, there's a chance the devs of the mod won't add it, and I can always do it myself using CraftTweaker.

**Comment by Gliese-832-c** [comment]
Storage Drawers, as well as Storage Drawers Extras are gone now. Thus, this issue can be closed.
