### ISSUE TITLE
[SUGGESTION] Make Storage Drawers Crafting based on Chisel

### ISSUE THREAD

**Issue by joendter** [Gliese-832-c/ad-astra-per-nucleon#38]
**Is your suggestion related to a problem? Please describe.**
I don't like that you already have to decide which type of drawer (1x1/1x2/2x2) you want to use, when crafting them.

**Describe the solution you'd like**
I would like if you could only craft the 1x1 variant and then chisel it to the other variants. I maybe would even go further and make it possible to chisel any drawer into any other drawer, even between different wood types, but that's maybe a bit too much.

**Additional context**
Just a little reminder...
I also tried making something like this myself but failed at the imo weird structure of the item-ids of Storage Drawers.

**Comment by kubulll** [comment]
i think that could cause too much problems to be worth it.

**Comment by joendter** [comment]
why do u think it would cause many problems?

**Comment by Gliese-832-c** [comment]
Interesting idea, but impossible to do now that Storage Drawers is being replaced.
