### ISSUE TITLE
Move the 'Water -> Steam' recipe to a different machine.

### ISSUE THREAD

**Issue by Gliese-832-c** [Gliese-832-c/ad-astra-per-nucleon#4]
**Describe the bug**
The recipe causes other recipes, which require water and something else, to create steam once that something else runs out.

**To Reproduce**
1. Try doing one of these other different recipes.
2. Let it run out of all inputs besides the water.
3. It will clog your production line up with steam.

**Expected behavior**
The production line should not be clogged up with steam.

**Screenshots**
_No need to._

**Computer specs (please complete the following information):**
_No need to._

**Additional context**
_No need to._

**Comment by ThePoleThatFishes** [comment]
Suggested Fix:
Implement a 3x3x3 steam boiler multiblock for electrical steam boiling. 
Input: 200 mB Water
Output: 1,000 mB Steam
Time: 100 ticks @ 50 RF/t (5,000 RF total cost)

**Comment by Gliese-832-c** [comment]
Fixed in v0.10! I added a new small multiblock machine called the Electric Fluid Heater, that, among some other recipes, boils water to steam!
