### ISSUE TITLE
[SUGGESTION]MSR Performance Improvement by making things smaller

### ISSUE THREAD

**Issue by Thalzamar** [Gliese-832-c/ad-astra-per-nucleon#8]
in the Configs:
Change CoolentPushMultiplier to 1.0
 when you update NC it should show up under MSR and HeatExchanger, allows HX and MSR of any size

Change CoolentHeatMultiplier to 30 or 25 
makes HX smaller but also less energy from Coolents

Change HPS rf/mb to 90, LPS to 22.5
compensation of the CoolentHeatMultiplier 

doing some Tests with CT how to make Condensers smaller sicne they don't have a config

**Comment by Thalzamar** [comment]
Optional Condenser stuff:
halves the Size of them since the heating required is halved
Exhaust 40->20
LQ 20->10

mods.nuclearcraft.condenser.removeAllRecipes();
mods.nuclearcraft.condenser.addRecipe([<liquid:exhaust_steam>*1000, <liquid:condensate_water>*50, 20.0 ,500]);
mods.nuclearcraft.condenser.addRecipe([<liquid:low_quality_steam>*1000, <liquid:condensate_water>*25, 10.0 , 350]);

**Comment by Gliese-832-c** [comment]
Some day I'll get to it...

**Comment by Gliese-832-c** [comment]
Doesn't matter anymore, now that NuclearCraft: Overhauled is in the pack as opposed to the old, normal NuclearCraft.
